var lista = new ListaSimple;
console.log("hola");
throw IndexOutOfBounds;
console.log("hola");
lista.addFirst("3");
lista.addFirst("2");
lista.addFirst("1");
lista.addLast("4");
lista.addLast("5");
lista.print();